### ISSUE TITLE
Please add a description of commands to the readme

### ISSUE THREAD

**Issue by Sayamame-beans** [anatawa12/vrc-get#44]
Probably I can run `vrc-get --help` after installation to know each feature, but I would like to know it before installing.
This will help people consider whether to install vrc-get.

**Comment by anatawa12** [comment]
It's hard work to keep sync with actual command output. That's why I don't want to add help message on README. If you actually want to know --help output before installation, you can see documentation comments on each command. https://github.com/anatawa12/vrc-get/blob/e21699a5d6628e4209ba3fc3bfb9c201c7d10791/src/commands.rs#L116-L119

Or do you know any tool to sync the help output? I can run such a tool on release process.
